// <auto-generated />
using System;
using HighlandGames.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HighlandGames.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423175416_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HighlandGames.Server.Models.Discipline", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = "sync",
                            Icon = "🏃",
                            Name = "Synchronlauf",
                            Number = 1,
                            Status = "upcoming"
                        },
                        new
                        {
                            Id = "weight",
                            Icon = "🏋️",
                            Name = "Gewichtlauf",
                            Number = 2,
                            Status = "upcoming"
                        },
                        new
                        {
                            Id = "caber",
                            Icon = "🪵",
                            Name = "Baumstammwerfen",
                            Number = 3,
                            Status = "upcoming"
                        },
                        new
                        {
                            Id = "rope",
                            Icon = "💪",
                            Name = "Seilziehen",
                            Number = 4,
                            Status = "upcoming"
                        },
                        new
                        {
                            Id = "fire",
                            Icon = "🔥",
                            Name = "Dustlöschen",
                            Number = 5,
                            Status = "upcoming"
                        });
                });

            modelBuilder.Entity("HighlandGames.Server.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Club")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("HighlandGames.Server.Models.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisciplineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("RawValue")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("ParticipantId", "DisciplineId")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("HighlandGames.Server.Models.Result", b =>
                {
                    b.HasOne("HighlandGames.Server.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HighlandGames.Server.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Participant");
                });
#pragma warning restore 612, 618
        }
    }
}
